// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: adam_api.proto
// Protobuf C++ Version: 6.31.1

#include "adam_api.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace adam_api {

inline constexpr OptimizeResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OptimizeResponse::OptimizeResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(OptimizeResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OptimizeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OptimizeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OptimizeResponseDefaultTypeInternal() {}
  union {
    OptimizeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OptimizeResponseDefaultTypeInternal _OptimizeResponse_default_instance_;

inline constexpr OptimizeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : left_edge_{},
        right_edge_{},
        params_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OptimizeRequest::OptimizeRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(OptimizeRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OptimizeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OptimizeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OptimizeRequestDefaultTypeInternal() {}
  union {
    OptimizeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OptimizeRequestDefaultTypeInternal _OptimizeRequest_default_instance_;

inline constexpr GlobalParamsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        learning_rate_{0},
        epsilon_{0},
        epochs_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GlobalParamsRequest::GlobalParamsRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GlobalParamsRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GlobalParamsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GlobalParamsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GlobalParamsRequestDefaultTypeInternal() {}
  union {
    GlobalParamsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GlobalParamsRequestDefaultTypeInternal _GlobalParamsRequest_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR EmptyResponse::EmptyResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(EmptyResponse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct EmptyResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyResponseDefaultTypeInternal() {}
  union {
    EmptyResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyResponseDefaultTypeInternal _EmptyResponse_default_instance_;
}  // namespace adam_api
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_adam_5fapi_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_adam_5fapi_2eproto = nullptr;
const ::uint32_t
    TableStruct_adam_5fapi_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::adam_api::GlobalParamsRequest, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::adam_api::GlobalParamsRequest, _impl_.learning_rate_),
        PROTOBUF_FIELD_OFFSET(::adam_api::GlobalParamsRequest, _impl_.epsilon_),
        PROTOBUF_FIELD_OFFSET(::adam_api::GlobalParamsRequest, _impl_.epochs_),
        0,
        1,
        2,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::adam_api::OptimizeRequest, _impl_.left_edge_),
        PROTOBUF_FIELD_OFFSET(::adam_api::OptimizeRequest, _impl_.right_edge_),
        PROTOBUF_FIELD_OFFSET(::adam_api::OptimizeRequest, _impl_.params_),
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::adam_api::OptimizeResponse, _impl_.result_),
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::adam_api::GlobalParamsRequest)},
        {9, sizeof(::adam_api::OptimizeRequest)},
        {13, sizeof(::adam_api::OptimizeResponse)},
        {15, sizeof(::adam_api::EmptyResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::adam_api::_GlobalParamsRequest_default_instance_._instance,
    &::adam_api::_OptimizeRequest_default_instance_._instance,
    &::adam_api::_OptimizeResponse_default_instance_._instance,
    &::adam_api::_EmptyResponse_default_instance_._instance,
};
const char descriptor_table_protodef_adam_5fapi_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016adam_api.proto\022\010adam_api\"M\n\023GlobalPara"
    "msRequest\022\025\n\rlearning_rate\030\001 \001(\001\022\017\n\007epsi"
    "lon\030\002 \001(\001\022\016\n\006epochs\030\003 \001(\005\"H\n\017OptimizeReq"
    "uest\022\021\n\tleft_edge\030\001 \003(\001\022\022\n\nright_edge\030\002 "
    "\003(\001\022\016\n\006params\030\003 \003(\001\"\"\n\020OptimizeResponse\022"
    "\016\n\006result\030\001 \003(\001\"\017\n\rEmptyResponse2\236\001\n\016Ada"
    "mApiService\022I\n\017SetGlobalParams\022\035.adam_ap"
    "i.GlobalParamsRequest\032\027.adam_api.EmptyRe"
    "sponse\022A\n\010Optimize\022\031.adam_api.OptimizeRe"
    "quest\032\032.adam_api.OptimizeResponseb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_adam_5fapi_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_adam_5fapi_2eproto = {
    false,
    false,
    401,
    descriptor_table_protodef_adam_5fapi_2eproto,
    "adam_api.proto",
    &descriptor_table_adam_5fapi_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_adam_5fapi_2eproto::offsets,
    file_level_enum_descriptors_adam_5fapi_2eproto,
    file_level_service_descriptors_adam_5fapi_2eproto,
};
namespace adam_api {
// ===================================================================

class GlobalParamsRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GlobalParamsRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_._has_bits_);
};

GlobalParamsRequest::GlobalParamsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GlobalParamsRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:adam_api.GlobalParamsRequest)
}
GlobalParamsRequest::GlobalParamsRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GlobalParamsRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GlobalParamsRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE GlobalParamsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void GlobalParamsRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, learning_rate_),
           0,
           offsetof(Impl_, epochs_) -
               offsetof(Impl_, learning_rate_) +
               sizeof(Impl_::epochs_));
}
GlobalParamsRequest::~GlobalParamsRequest() {
  // @@protoc_insertion_point(destructor:adam_api.GlobalParamsRequest)
  SharedDtor(*this);
}
inline void GlobalParamsRequest::SharedDtor(MessageLite& self) {
  GlobalParamsRequest& this_ = static_cast<GlobalParamsRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GlobalParamsRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GlobalParamsRequest(arena);
}
constexpr auto GlobalParamsRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GlobalParamsRequest),
                                            alignof(GlobalParamsRequest));
}
constexpr auto GlobalParamsRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GlobalParamsRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GlobalParamsRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GlobalParamsRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GlobalParamsRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GlobalParamsRequest>(), &GlobalParamsRequest::ByteSizeLong,
              &GlobalParamsRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_._cached_size_),
          false,
      },
      &GlobalParamsRequest::kDescriptorMethods,
      &descriptor_table_adam_5fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GlobalParamsRequest_class_data_ =
        GlobalParamsRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GlobalParamsRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GlobalParamsRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GlobalParamsRequest_class_data_.tc_table);
  return GlobalParamsRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
GlobalParamsRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GlobalParamsRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::adam_api::GlobalParamsRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double learning_rate = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 0, 0, PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_.learning_rate_)}},
    // double epsilon = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0, PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_.epsilon_)}},
    // int32 epochs = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GlobalParamsRequest, _impl_.epochs_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_.epochs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double learning_rate = 1;
    {PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_.learning_rate_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double epsilon = 2;
    {PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_.epsilon_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // int32 epochs = 3;
    {PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_.epochs_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void GlobalParamsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:adam_api.GlobalParamsRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    ::memset(&_impl_.learning_rate_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.epochs_) -
        reinterpret_cast<char*>(&_impl_.learning_rate_)) + sizeof(_impl_.epochs_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GlobalParamsRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GlobalParamsRequest& this_ = static_cast<const GlobalParamsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GlobalParamsRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GlobalParamsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:adam_api.GlobalParamsRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double learning_rate = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_learning_rate()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          1, this_._internal_learning_rate(), target);
    }
  }

  // double epsilon = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_epsilon()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_epsilon(), target);
    }
  }

  // int32 epochs = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_epochs() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_epochs(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:adam_api.GlobalParamsRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GlobalParamsRequest::ByteSizeLong(const MessageLite& base) {
  const GlobalParamsRequest& this_ = static_cast<const GlobalParamsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GlobalParamsRequest::ByteSizeLong() const {
  const GlobalParamsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:adam_api.GlobalParamsRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // double learning_rate = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_learning_rate()) != 0) {
        total_size += 9;
      }
    }
    // double epsilon = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_epsilon()) != 0) {
        total_size += 9;
      }
    }
    // int32 epochs = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_epochs() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_epochs());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GlobalParamsRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GlobalParamsRequest*>(&to_msg);
  auto& from = static_cast<const GlobalParamsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:adam_api.GlobalParamsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_learning_rate()) != 0) {
        _this->_impl_.learning_rate_ = from._impl_.learning_rate_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_epsilon()) != 0) {
        _this->_impl_.epsilon_ = from._impl_.epsilon_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_epochs() != 0) {
        _this->_impl_.epochs_ = from._impl_.epochs_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GlobalParamsRequest::CopyFrom(const GlobalParamsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:adam_api.GlobalParamsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GlobalParamsRequest::InternalSwap(GlobalParamsRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_.epochs_)
      + sizeof(GlobalParamsRequest::_impl_.epochs_)
      - PROTOBUF_FIELD_OFFSET(GlobalParamsRequest, _impl_.learning_rate_)>(
          reinterpret_cast<char*>(&_impl_.learning_rate_),
          reinterpret_cast<char*>(&other->_impl_.learning_rate_));
}

::google::protobuf::Metadata GlobalParamsRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OptimizeRequest::_Internal {
 public:
};

OptimizeRequest::OptimizeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OptimizeRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:adam_api.OptimizeRequest)
}
PROTOBUF_NDEBUG_INLINE OptimizeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::adam_api::OptimizeRequest& from_msg)
      : left_edge_{visibility, arena, from.left_edge_},
        right_edge_{visibility, arena, from.right_edge_},
        params_{visibility, arena, from.params_},
        _cached_size_{0} {}

OptimizeRequest::OptimizeRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const OptimizeRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OptimizeRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OptimizeRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:adam_api.OptimizeRequest)
}
PROTOBUF_NDEBUG_INLINE OptimizeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : left_edge_{visibility, arena},
        right_edge_{visibility, arena},
        params_{visibility, arena},
        _cached_size_{0} {}

inline void OptimizeRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
OptimizeRequest::~OptimizeRequest() {
  // @@protoc_insertion_point(destructor:adam_api.OptimizeRequest)
  SharedDtor(*this);
}
inline void OptimizeRequest::SharedDtor(MessageLite& self) {
  OptimizeRequest& this_ = static_cast<OptimizeRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL OptimizeRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) OptimizeRequest(arena);
}
constexpr auto OptimizeRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.left_edge_) +
          decltype(OptimizeRequest::_impl_.left_edge_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.right_edge_) +
          decltype(OptimizeRequest::_impl_.right_edge_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.params_) +
          decltype(OptimizeRequest::_impl_.params_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(OptimizeRequest), alignof(OptimizeRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&OptimizeRequest::PlacementNew_,
                                 sizeof(OptimizeRequest),
                                 alignof(OptimizeRequest));
  }
}
constexpr auto OptimizeRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_OptimizeRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &OptimizeRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<OptimizeRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &OptimizeRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<OptimizeRequest>(), &OptimizeRequest::ByteSizeLong,
              &OptimizeRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_._cached_size_),
          false,
      },
      &OptimizeRequest::kDescriptorMethods,
      &descriptor_table_adam_5fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull OptimizeRequest_class_data_ =
        OptimizeRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
OptimizeRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&OptimizeRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(OptimizeRequest_class_data_.tc_table);
  return OptimizeRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
OptimizeRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    OptimizeRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::adam_api::OptimizeRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated double left_edge = 1;
    {::_pbi::TcParser::FastF64P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.left_edge_)}},
    // repeated double right_edge = 2;
    {::_pbi::TcParser::FastF64P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.right_edge_)}},
    // repeated double params = 3;
    {::_pbi::TcParser::FastF64P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.params_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated double left_edge = 1;
    {PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.left_edge_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double right_edge = 2;
    {PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.right_edge_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double params = 3;
    {PROTOBUF_FIELD_OFFSET(OptimizeRequest, _impl_.params_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void OptimizeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:adam_api.OptimizeRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.left_edge_.Clear();
  _impl_.right_edge_.Clear();
  _impl_.params_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL OptimizeRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const OptimizeRequest& this_ = static_cast<const OptimizeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL OptimizeRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const OptimizeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:adam_api.OptimizeRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated double left_edge = 1;
  if (this_._internal_left_edge_size() > 0) {
    target = stream->WriteFixedPacked(1, this_._internal_left_edge(), target);
  }

  // repeated double right_edge = 2;
  if (this_._internal_right_edge_size() > 0) {
    target = stream->WriteFixedPacked(2, this_._internal_right_edge(), target);
  }

  // repeated double params = 3;
  if (this_._internal_params_size() > 0) {
    target = stream->WriteFixedPacked(3, this_._internal_params(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:adam_api.OptimizeRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t OptimizeRequest::ByteSizeLong(const MessageLite& base) {
  const OptimizeRequest& this_ = static_cast<const OptimizeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t OptimizeRequest::ByteSizeLong() const {
  const OptimizeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:adam_api.OptimizeRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated double left_edge = 1;
    {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_left_edge_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double right_edge = 2;
    {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_right_edge_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double params = 3;
    {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_params_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void OptimizeRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OptimizeRequest*>(&to_msg);
  auto& from = static_cast<const OptimizeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:adam_api.OptimizeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_left_edge()->MergeFrom(from._internal_left_edge());
  _this->_internal_mutable_right_edge()->MergeFrom(from._internal_right_edge());
  _this->_internal_mutable_params()->MergeFrom(from._internal_params());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OptimizeRequest::CopyFrom(const OptimizeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:adam_api.OptimizeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OptimizeRequest::InternalSwap(OptimizeRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.left_edge_.InternalSwap(&other->_impl_.left_edge_);
  _impl_.right_edge_.InternalSwap(&other->_impl_.right_edge_);
  _impl_.params_.InternalSwap(&other->_impl_.params_);
}

::google::protobuf::Metadata OptimizeRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OptimizeResponse::_Internal {
 public:
};

OptimizeResponse::OptimizeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OptimizeResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:adam_api.OptimizeResponse)
}
PROTOBUF_NDEBUG_INLINE OptimizeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::adam_api::OptimizeResponse& from_msg)
      : result_{visibility, arena, from.result_},
        _cached_size_{0} {}

OptimizeResponse::OptimizeResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const OptimizeResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OptimizeResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OptimizeResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:adam_api.OptimizeResponse)
}
PROTOBUF_NDEBUG_INLINE OptimizeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : result_{visibility, arena},
        _cached_size_{0} {}

inline void OptimizeResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
OptimizeResponse::~OptimizeResponse() {
  // @@protoc_insertion_point(destructor:adam_api.OptimizeResponse)
  SharedDtor(*this);
}
inline void OptimizeResponse::SharedDtor(MessageLite& self) {
  OptimizeResponse& this_ = static_cast<OptimizeResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL OptimizeResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) OptimizeResponse(arena);
}
constexpr auto OptimizeResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(OptimizeResponse, _impl_.result_) +
          decltype(OptimizeResponse::_impl_.result_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(OptimizeResponse), alignof(OptimizeResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&OptimizeResponse::PlacementNew_,
                                 sizeof(OptimizeResponse),
                                 alignof(OptimizeResponse));
  }
}
constexpr auto OptimizeResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_OptimizeResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &OptimizeResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<OptimizeResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &OptimizeResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<OptimizeResponse>(), &OptimizeResponse::ByteSizeLong,
              &OptimizeResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(OptimizeResponse, _impl_._cached_size_),
          false,
      },
      &OptimizeResponse::kDescriptorMethods,
      &descriptor_table_adam_5fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull OptimizeResponse_class_data_ =
        OptimizeResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
OptimizeResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&OptimizeResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(OptimizeResponse_class_data_.tc_table);
  return OptimizeResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
OptimizeResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    OptimizeResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::adam_api::OptimizeResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated double result = 1;
    {::_pbi::TcParser::FastF64P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(OptimizeResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated double result = 1;
    {PROTOBUF_FIELD_OFFSET(OptimizeResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void OptimizeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:adam_api.OptimizeResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL OptimizeResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const OptimizeResponse& this_ = static_cast<const OptimizeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL OptimizeResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const OptimizeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:adam_api.OptimizeResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated double result = 1;
  if (this_._internal_result_size() > 0) {
    target = stream->WriteFixedPacked(1, this_._internal_result(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:adam_api.OptimizeResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t OptimizeResponse::ByteSizeLong(const MessageLite& base) {
  const OptimizeResponse& this_ = static_cast<const OptimizeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t OptimizeResponse::ByteSizeLong() const {
  const OptimizeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:adam_api.OptimizeResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated double result = 1;
    {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_result_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void OptimizeResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OptimizeResponse*>(&to_msg);
  auto& from = static_cast<const OptimizeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:adam_api.OptimizeResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_result()->MergeFrom(from._internal_result());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OptimizeResponse::CopyFrom(const OptimizeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:adam_api.OptimizeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OptimizeResponse::InternalSwap(OptimizeResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.result_.InternalSwap(&other->_impl_.result_);
}

::google::protobuf::Metadata OptimizeResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EmptyResponse::_Internal {
 public:
};

EmptyResponse::EmptyResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, EmptyResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:adam_api.EmptyResponse)
}
EmptyResponse::EmptyResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EmptyResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, EmptyResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EmptyResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:adam_api.EmptyResponse)
}

inline void* PROTOBUF_NONNULL EmptyResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EmptyResponse(arena);
}
constexpr auto EmptyResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EmptyResponse),
                                            alignof(EmptyResponse));
}
constexpr auto EmptyResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EmptyResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EmptyResponse::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<EmptyResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EmptyResponse::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<EmptyResponse>(), &EmptyResponse::ByteSizeLong,
              &EmptyResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EmptyResponse, _impl_._cached_size_),
          false,
      },
      &EmptyResponse::kDescriptorMethods,
      &descriptor_table_adam_5fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EmptyResponse_class_data_ =
        EmptyResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EmptyResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EmptyResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EmptyResponse_class_data_.tc_table);
  return EmptyResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
EmptyResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EmptyResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::adam_api::EmptyResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata EmptyResponse::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace adam_api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_adam_5fapi_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
