// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: adam_api.proto
// Protobuf C++ Version: 6.33.0-dev

#ifndef adam_5fapi_2eproto_2epb_2eh
#define adam_5fapi_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_adam_5fapi_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_adam_5fapi_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_adam_5fapi_2eproto;
}  // extern "C"
namespace adam_api {
class EmptyResponse;
struct EmptyResponseDefaultTypeInternal;
extern EmptyResponseDefaultTypeInternal _EmptyResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull EmptyResponse_class_data_;
class GlobalParamsRequest;
struct GlobalParamsRequestDefaultTypeInternal;
extern GlobalParamsRequestDefaultTypeInternal _GlobalParamsRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GlobalParamsRequest_class_data_;
class OptimizeRequest;
struct OptimizeRequestDefaultTypeInternal;
extern OptimizeRequestDefaultTypeInternal _OptimizeRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OptimizeRequest_class_data_;
class OptimizeResponse;
struct OptimizeResponseDefaultTypeInternal;
extern OptimizeResponseDefaultTypeInternal _OptimizeResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OptimizeResponse_class_data_;
}  // namespace adam_api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace adam_api {

// ===================================================================


// -------------------------------------------------------------------

class OptimizeResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:adam_api.OptimizeResponse) */ {
 public:
  inline OptimizeResponse() : OptimizeResponse(nullptr) {}
  ~OptimizeResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OptimizeResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OptimizeResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OptimizeResponse(::google::protobuf::internal::ConstantInitialized);

  inline OptimizeResponse(const OptimizeResponse& from) : OptimizeResponse(nullptr, from) {}
  inline OptimizeResponse(OptimizeResponse&& from) noexcept
      : OptimizeResponse(nullptr, ::std::move(from)) {}
  inline OptimizeResponse& operator=(const OptimizeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline OptimizeResponse& operator=(OptimizeResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OptimizeResponse& default_instance() {
    return *reinterpret_cast<const OptimizeResponse*>(
        &_OptimizeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(OptimizeResponse& a, OptimizeResponse& b) { a.Swap(&b); }
  inline void Swap(OptimizeResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OptimizeResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OptimizeResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OptimizeResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OptimizeResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OptimizeResponse& from) { OptimizeResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OptimizeResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "adam_api.OptimizeResponse"; }

  explicit OptimizeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OptimizeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OptimizeResponse& from);
  OptimizeResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OptimizeResponse&& from) noexcept
      : OptimizeResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // repeated double result = 1;
  int result_size() const;
  private:
  int _internal_result_size() const;

  public:
  void clear_result() ;
  double result(int index) const;
  void set_result(int index, double value);
  void add_result(double value);
  const ::google::protobuf::RepeatedField<double>& result() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_result();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_result() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_result();

  public:
  // @@protoc_insertion_point(class_scope:adam_api.OptimizeResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OptimizeResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adam_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OptimizeResponse_class_data_;
// -------------------------------------------------------------------

class OptimizeRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:adam_api.OptimizeRequest) */ {
 public:
  inline OptimizeRequest() : OptimizeRequest(nullptr) {}
  ~OptimizeRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OptimizeRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OptimizeRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OptimizeRequest(::google::protobuf::internal::ConstantInitialized);

  inline OptimizeRequest(const OptimizeRequest& from) : OptimizeRequest(nullptr, from) {}
  inline OptimizeRequest(OptimizeRequest&& from) noexcept
      : OptimizeRequest(nullptr, ::std::move(from)) {}
  inline OptimizeRequest& operator=(const OptimizeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OptimizeRequest& operator=(OptimizeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OptimizeRequest& default_instance() {
    return *reinterpret_cast<const OptimizeRequest*>(
        &_OptimizeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(OptimizeRequest& a, OptimizeRequest& b) { a.Swap(&b); }
  inline void Swap(OptimizeRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OptimizeRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OptimizeRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OptimizeRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OptimizeRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OptimizeRequest& from) { OptimizeRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OptimizeRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "adam_api.OptimizeRequest"; }

  explicit OptimizeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OptimizeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OptimizeRequest& from);
  OptimizeRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OptimizeRequest&& from) noexcept
      : OptimizeRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kParamsFieldNumber = 1,
  };
  // repeated double params = 1;
  int params_size() const;
  private:
  int _internal_params_size() const;

  public:
  void clear_params() ;
  double params(int index) const;
  void set_params(int index, double value);
  void add_params(double value);
  const ::google::protobuf::RepeatedField<double>& params() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_params();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_params() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_params();

  public:
  // @@protoc_insertion_point(class_scope:adam_api.OptimizeRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OptimizeRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> params_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adam_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OptimizeRequest_class_data_;
// -------------------------------------------------------------------

class GlobalParamsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:adam_api.GlobalParamsRequest) */ {
 public:
  inline GlobalParamsRequest() : GlobalParamsRequest(nullptr) {}
  ~GlobalParamsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GlobalParamsRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GlobalParamsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GlobalParamsRequest(::google::protobuf::internal::ConstantInitialized);

  inline GlobalParamsRequest(const GlobalParamsRequest& from) : GlobalParamsRequest(nullptr, from) {}
  inline GlobalParamsRequest(GlobalParamsRequest&& from) noexcept
      : GlobalParamsRequest(nullptr, ::std::move(from)) {}
  inline GlobalParamsRequest& operator=(const GlobalParamsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GlobalParamsRequest& operator=(GlobalParamsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GlobalParamsRequest& default_instance() {
    return *reinterpret_cast<const GlobalParamsRequest*>(
        &_GlobalParamsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GlobalParamsRequest& a, GlobalParamsRequest& b) { a.Swap(&b); }
  inline void Swap(GlobalParamsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GlobalParamsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GlobalParamsRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GlobalParamsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GlobalParamsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GlobalParamsRequest& from) { GlobalParamsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GlobalParamsRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "adam_api.GlobalParamsRequest"; }

  explicit GlobalParamsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GlobalParamsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GlobalParamsRequest& from);
  GlobalParamsRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GlobalParamsRequest&& from) noexcept
      : GlobalParamsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLeftEdgeFieldNumber = 2,
    kRightEdgeFieldNumber = 3,
    kLearningRateFieldNumber = 1,
    kEpochsFieldNumber = 4,
  };
  // repeated double left_edge = 2;
  int left_edge_size() const;
  private:
  int _internal_left_edge_size() const;

  public:
  void clear_left_edge() ;
  double left_edge(int index) const;
  void set_left_edge(int index, double value);
  void add_left_edge(double value);
  const ::google::protobuf::RepeatedField<double>& left_edge() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_left_edge();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_left_edge() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_left_edge();

  public:
  // repeated double right_edge = 3;
  int right_edge_size() const;
  private:
  int _internal_right_edge_size() const;

  public:
  void clear_right_edge() ;
  double right_edge(int index) const;
  void set_right_edge(int index, double value);
  void add_right_edge(double value);
  const ::google::protobuf::RepeatedField<double>& right_edge() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_right_edge();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_right_edge() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_right_edge();

  public:
  // double learning_rate = 1;
  void clear_learning_rate() ;
  double learning_rate() const;
  void set_learning_rate(double value);

  private:
  double _internal_learning_rate() const;
  void _internal_set_learning_rate(double value);

  public:
  // int32 epochs = 4;
  void clear_epochs() ;
  ::int32_t epochs() const;
  void set_epochs(::int32_t value);

  private:
  ::int32_t _internal_epochs() const;
  void _internal_set_epochs(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:adam_api.GlobalParamsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GlobalParamsRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> left_edge_;
    ::google::protobuf::RepeatedField<double> right_edge_;
    double learning_rate_;
    ::int32_t epochs_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adam_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GlobalParamsRequest_class_data_;
// -------------------------------------------------------------------

class EmptyResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:adam_api.EmptyResponse) */ {
 public:
  inline EmptyResponse() : EmptyResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EmptyResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EmptyResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EmptyResponse(::google::protobuf::internal::ConstantInitialized);

  inline EmptyResponse(const EmptyResponse& from) : EmptyResponse(nullptr, from) {}
  inline EmptyResponse(EmptyResponse&& from) noexcept
      : EmptyResponse(nullptr, ::std::move(from)) {}
  inline EmptyResponse& operator=(const EmptyResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmptyResponse& operator=(EmptyResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EmptyResponse& default_instance() {
    return *reinterpret_cast<const EmptyResponse*>(
        &_EmptyResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(EmptyResponse& a, EmptyResponse& b) { a.Swap(&b); }
  inline void Swap(EmptyResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmptyResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EmptyResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<EmptyResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const EmptyResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const EmptyResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "adam_api.EmptyResponse"; }

  explicit EmptyResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EmptyResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EmptyResponse& from);
  EmptyResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EmptyResponse&& from) noexcept
      : EmptyResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:adam_api.EmptyResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_adam_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull EmptyResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GlobalParamsRequest

// double learning_rate = 1;
inline void GlobalParamsRequest::clear_learning_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.learning_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double GlobalParamsRequest::learning_rate() const {
  // @@protoc_insertion_point(field_get:adam_api.GlobalParamsRequest.learning_rate)
  return _internal_learning_rate();
}
inline void GlobalParamsRequest::set_learning_rate(double value) {
  _internal_set_learning_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:adam_api.GlobalParamsRequest.learning_rate)
}
inline double GlobalParamsRequest::_internal_learning_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.learning_rate_;
}
inline void GlobalParamsRequest::_internal_set_learning_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.learning_rate_ = value;
}

// repeated double left_edge = 2;
inline int GlobalParamsRequest::_internal_left_edge_size() const {
  return _internal_left_edge().size();
}
inline int GlobalParamsRequest::left_edge_size() const {
  return _internal_left_edge_size();
}
inline void GlobalParamsRequest::clear_left_edge() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_edge_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double GlobalParamsRequest::left_edge(int index) const {
  // @@protoc_insertion_point(field_get:adam_api.GlobalParamsRequest.left_edge)
  return _internal_left_edge().Get(index);
}
inline void GlobalParamsRequest::set_left_edge(int index, double value) {
  _internal_mutable_left_edge()->Set(index, value);
  // @@protoc_insertion_point(field_set:adam_api.GlobalParamsRequest.left_edge)
}
inline void GlobalParamsRequest::add_left_edge(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_left_edge()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:adam_api.GlobalParamsRequest.left_edge)
}
inline const ::google::protobuf::RepeatedField<double>& GlobalParamsRequest::left_edge() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:adam_api.GlobalParamsRequest.left_edge)
  return _internal_left_edge();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL GlobalParamsRequest::mutable_left_edge()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:adam_api.GlobalParamsRequest.left_edge)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_left_edge();
}
inline const ::google::protobuf::RepeatedField<double>&
GlobalParamsRequest::_internal_left_edge() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_edge_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
GlobalParamsRequest::_internal_mutable_left_edge() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.left_edge_;
}

// repeated double right_edge = 3;
inline int GlobalParamsRequest::_internal_right_edge_size() const {
  return _internal_right_edge().size();
}
inline int GlobalParamsRequest::right_edge_size() const {
  return _internal_right_edge_size();
}
inline void GlobalParamsRequest::clear_right_edge() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_edge_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double GlobalParamsRequest::right_edge(int index) const {
  // @@protoc_insertion_point(field_get:adam_api.GlobalParamsRequest.right_edge)
  return _internal_right_edge().Get(index);
}
inline void GlobalParamsRequest::set_right_edge(int index, double value) {
  _internal_mutable_right_edge()->Set(index, value);
  // @@protoc_insertion_point(field_set:adam_api.GlobalParamsRequest.right_edge)
}
inline void GlobalParamsRequest::add_right_edge(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_right_edge()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:adam_api.GlobalParamsRequest.right_edge)
}
inline const ::google::protobuf::RepeatedField<double>& GlobalParamsRequest::right_edge() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:adam_api.GlobalParamsRequest.right_edge)
  return _internal_right_edge();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL GlobalParamsRequest::mutable_right_edge()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:adam_api.GlobalParamsRequest.right_edge)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_right_edge();
}
inline const ::google::protobuf::RepeatedField<double>&
GlobalParamsRequest::_internal_right_edge() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_edge_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
GlobalParamsRequest::_internal_mutable_right_edge() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.right_edge_;
}

// int32 epochs = 4;
inline void GlobalParamsRequest::clear_epochs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.epochs_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t GlobalParamsRequest::epochs() const {
  // @@protoc_insertion_point(field_get:adam_api.GlobalParamsRequest.epochs)
  return _internal_epochs();
}
inline void GlobalParamsRequest::set_epochs(::int32_t value) {
  _internal_set_epochs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:adam_api.GlobalParamsRequest.epochs)
}
inline ::int32_t GlobalParamsRequest::_internal_epochs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.epochs_;
}
inline void GlobalParamsRequest::_internal_set_epochs(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.epochs_ = value;
}

// -------------------------------------------------------------------

// OptimizeRequest

// repeated double params = 1;
inline int OptimizeRequest::_internal_params_size() const {
  return _internal_params().size();
}
inline int OptimizeRequest::params_size() const {
  return _internal_params_size();
}
inline void OptimizeRequest::clear_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.params_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double OptimizeRequest::params(int index) const {
  // @@protoc_insertion_point(field_get:adam_api.OptimizeRequest.params)
  return _internal_params().Get(index);
}
inline void OptimizeRequest::set_params(int index, double value) {
  _internal_mutable_params()->Set(index, value);
  // @@protoc_insertion_point(field_set:adam_api.OptimizeRequest.params)
}
inline void OptimizeRequest::add_params(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_params()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:adam_api.OptimizeRequest.params)
}
inline const ::google::protobuf::RepeatedField<double>& OptimizeRequest::params() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:adam_api.OptimizeRequest.params)
  return _internal_params();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL OptimizeRequest::mutable_params()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:adam_api.OptimizeRequest.params)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_params();
}
inline const ::google::protobuf::RepeatedField<double>&
OptimizeRequest::_internal_params() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.params_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
OptimizeRequest::_internal_mutable_params() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.params_;
}

// -------------------------------------------------------------------

// OptimizeResponse

// repeated double result = 1;
inline int OptimizeResponse::_internal_result_size() const {
  return _internal_result().size();
}
inline int OptimizeResponse::result_size() const {
  return _internal_result_size();
}
inline void OptimizeResponse::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double OptimizeResponse::result(int index) const {
  // @@protoc_insertion_point(field_get:adam_api.OptimizeResponse.result)
  return _internal_result().Get(index);
}
inline void OptimizeResponse::set_result(int index, double value) {
  _internal_mutable_result()->Set(index, value);
  // @@protoc_insertion_point(field_set:adam_api.OptimizeResponse.result)
}
inline void OptimizeResponse::add_result(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_result()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:adam_api.OptimizeResponse.result)
}
inline const ::google::protobuf::RepeatedField<double>& OptimizeResponse::result() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:adam_api.OptimizeResponse.result)
  return _internal_result();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL OptimizeResponse::mutable_result()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:adam_api.OptimizeResponse.result)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_result();
}
inline const ::google::protobuf::RepeatedField<double>&
OptimizeResponse::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
OptimizeResponse::_internal_mutable_result() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.result_;
}

// -------------------------------------------------------------------

// EmptyResponse

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace adam_api


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // adam_5fapi_2eproto_2epb_2eh
