// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core.proto
// Protobuf C++ Version: 6.33.0-dev

#ifndef core_2eproto_2epb_2eh
#define core_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_core_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_core_2eproto;
}  // extern "C"
namespace core_api {
class OptimalRequest;
struct OptimalRequestDefaultTypeInternal;
extern OptimalRequestDefaultTypeInternal _OptimalRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OptimalRequest_class_data_;
class OptimalResponse;
struct OptimalResponseDefaultTypeInternal;
extern OptimalResponseDefaultTypeInternal _OptimalResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OptimalResponse_class_data_;
class OptimizeParamsRequest;
struct OptimizeParamsRequestDefaultTypeInternal;
extern OptimizeParamsRequestDefaultTypeInternal _OptimizeParamsRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OptimizeParamsRequest_class_data_;
class OptimizeParamsResponse;
struct OptimizeParamsResponseDefaultTypeInternal;
extern OptimizeParamsResponseDefaultTypeInternal _OptimizeParamsResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OptimizeParamsResponse_class_data_;
}  // namespace core_api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace core_api {

// ===================================================================


// -------------------------------------------------------------------

class OptimizeParamsResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:core_api.OptimizeParamsResponse) */ {
 public:
  inline OptimizeParamsResponse() : OptimizeParamsResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OptimizeParamsResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OptimizeParamsResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OptimizeParamsResponse(::google::protobuf::internal::ConstantInitialized);

  inline OptimizeParamsResponse(const OptimizeParamsResponse& from) : OptimizeParamsResponse(nullptr, from) {}
  inline OptimizeParamsResponse(OptimizeParamsResponse&& from) noexcept
      : OptimizeParamsResponse(nullptr, ::std::move(from)) {}
  inline OptimizeParamsResponse& operator=(const OptimizeParamsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline OptimizeParamsResponse& operator=(OptimizeParamsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OptimizeParamsResponse& default_instance() {
    return *reinterpret_cast<const OptimizeParamsResponse*>(
        &_OptimizeParamsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(OptimizeParamsResponse& a, OptimizeParamsResponse& b) { a.Swap(&b); }
  inline void Swap(OptimizeParamsResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OptimizeParamsResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OptimizeParamsResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<OptimizeParamsResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const OptimizeParamsResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const OptimizeParamsResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "core_api.OptimizeParamsResponse"; }

  explicit OptimizeParamsResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OptimizeParamsResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OptimizeParamsResponse& from);
  OptimizeParamsResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OptimizeParamsResponse&& from) noexcept
      : OptimizeParamsResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:core_api.OptimizeParamsResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_core_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OptimizeParamsResponse_class_data_;
// -------------------------------------------------------------------

class OptimizeParamsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:core_api.OptimizeParamsRequest) */ {
 public:
  inline OptimizeParamsRequest() : OptimizeParamsRequest(nullptr) {}
  ~OptimizeParamsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OptimizeParamsRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OptimizeParamsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OptimizeParamsRequest(::google::protobuf::internal::ConstantInitialized);

  inline OptimizeParamsRequest(const OptimizeParamsRequest& from) : OptimizeParamsRequest(nullptr, from) {}
  inline OptimizeParamsRequest(OptimizeParamsRequest&& from) noexcept
      : OptimizeParamsRequest(nullptr, ::std::move(from)) {}
  inline OptimizeParamsRequest& operator=(const OptimizeParamsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OptimizeParamsRequest& operator=(OptimizeParamsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OptimizeParamsRequest& default_instance() {
    return *reinterpret_cast<const OptimizeParamsRequest*>(
        &_OptimizeParamsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(OptimizeParamsRequest& a, OptimizeParamsRequest& b) { a.Swap(&b); }
  inline void Swap(OptimizeParamsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OptimizeParamsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OptimizeParamsRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OptimizeParamsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OptimizeParamsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OptimizeParamsRequest& from) { OptimizeParamsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OptimizeParamsRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "core_api.OptimizeParamsRequest"; }

  explicit OptimizeParamsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OptimizeParamsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OptimizeParamsRequest& from);
  OptimizeParamsRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OptimizeParamsRequest&& from) noexcept
      : OptimizeParamsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLeftEdgeFieldNumber = 2,
    kRightEdgeFieldNumber = 3,
    kLearningRateFieldNumber = 1,
    kEpochsFieldNumber = 4,
  };
  // repeated double left_edge = 2;
  int left_edge_size() const;
  private:
  int _internal_left_edge_size() const;

  public:
  void clear_left_edge() ;
  double left_edge(int index) const;
  void set_left_edge(int index, double value);
  void add_left_edge(double value);
  const ::google::protobuf::RepeatedField<double>& left_edge() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_left_edge();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_left_edge() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_left_edge();

  public:
  // repeated double right_edge = 3;
  int right_edge_size() const;
  private:
  int _internal_right_edge_size() const;

  public:
  void clear_right_edge() ;
  double right_edge(int index) const;
  void set_right_edge(int index, double value);
  void add_right_edge(double value);
  const ::google::protobuf::RepeatedField<double>& right_edge() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_right_edge();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_right_edge() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_right_edge();

  public:
  // double learning_rate = 1;
  void clear_learning_rate() ;
  double learning_rate() const;
  void set_learning_rate(double value);

  private:
  double _internal_learning_rate() const;
  void _internal_set_learning_rate(double value);

  public:
  // int32 epochs = 4;
  void clear_epochs() ;
  ::int32_t epochs() const;
  void set_epochs(::int32_t value);

  private:
  ::int32_t _internal_epochs() const;
  void _internal_set_epochs(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:core_api.OptimizeParamsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OptimizeParamsRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> left_edge_;
    ::google::protobuf::RepeatedField<double> right_edge_;
    double learning_rate_;
    ::int32_t epochs_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OptimizeParamsRequest_class_data_;
// -------------------------------------------------------------------

class OptimalResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:core_api.OptimalResponse) */ {
 public:
  inline OptimalResponse() : OptimalResponse(nullptr) {}
  ~OptimalResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OptimalResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OptimalResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OptimalResponse(::google::protobuf::internal::ConstantInitialized);

  inline OptimalResponse(const OptimalResponse& from) : OptimalResponse(nullptr, from) {}
  inline OptimalResponse(OptimalResponse&& from) noexcept
      : OptimalResponse(nullptr, ::std::move(from)) {}
  inline OptimalResponse& operator=(const OptimalResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline OptimalResponse& operator=(OptimalResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OptimalResponse& default_instance() {
    return *reinterpret_cast<const OptimalResponse*>(
        &_OptimalResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(OptimalResponse& a, OptimalResponse& b) { a.Swap(&b); }
  inline void Swap(OptimalResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OptimalResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OptimalResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OptimalResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OptimalResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OptimalResponse& from) { OptimalResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OptimalResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "core_api.OptimalResponse"; }

  explicit OptimalResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OptimalResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OptimalResponse& from);
  OptimalResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OptimalResponse&& from) noexcept
      : OptimalResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOptimPathFieldNumber = 1,
    kOptimControlFieldNumber = 2,
    kOptimPathSizeRowFieldNumber = 3,
    kOptimPathSizeColFieldNumber = 4,
    kOptimControlSizeRowFieldNumber = 5,
    kOptimControlSizeColFieldNumber = 6,
    kFunctionalValueFieldNumber = 7,
  };
  // repeated double optim_path = 1;
  int optim_path_size() const;
  private:
  int _internal_optim_path_size() const;

  public:
  void clear_optim_path() ;
  double optim_path(int index) const;
  void set_optim_path(int index, double value);
  void add_optim_path(double value);
  const ::google::protobuf::RepeatedField<double>& optim_path() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_optim_path();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_optim_path() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_optim_path();

  public:
  // repeated double optim_control = 2;
  int optim_control_size() const;
  private:
  int _internal_optim_control_size() const;

  public:
  void clear_optim_control() ;
  double optim_control(int index) const;
  void set_optim_control(int index, double value);
  void add_optim_control(double value);
  const ::google::protobuf::RepeatedField<double>& optim_control() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_optim_control();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_optim_control() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_optim_control();

  public:
  // int32 optim_path_size_row = 3;
  void clear_optim_path_size_row() ;
  ::int32_t optim_path_size_row() const;
  void set_optim_path_size_row(::int32_t value);

  private:
  ::int32_t _internal_optim_path_size_row() const;
  void _internal_set_optim_path_size_row(::int32_t value);

  public:
  // int32 optim_path_size_col = 4;
  void clear_optim_path_size_col() ;
  ::int32_t optim_path_size_col() const;
  void set_optim_path_size_col(::int32_t value);

  private:
  ::int32_t _internal_optim_path_size_col() const;
  void _internal_set_optim_path_size_col(::int32_t value);

  public:
  // int32 optim_control_size_row = 5;
  void clear_optim_control_size_row() ;
  ::int32_t optim_control_size_row() const;
  void set_optim_control_size_row(::int32_t value);

  private:
  ::int32_t _internal_optim_control_size_row() const;
  void _internal_set_optim_control_size_row(::int32_t value);

  public:
  // int32 optim_control_size_col = 6;
  void clear_optim_control_size_col() ;
  ::int32_t optim_control_size_col() const;
  void set_optim_control_size_col(::int32_t value);

  private:
  ::int32_t _internal_optim_control_size_col() const;
  void _internal_set_optim_control_size_col(::int32_t value);

  public:
  // double functional_value = 7;
  void clear_functional_value() ;
  double functional_value() const;
  void set_functional_value(double value);

  private:
  double _internal_functional_value() const;
  void _internal_set_functional_value(double value);

  public:
  // @@protoc_insertion_point(class_scope:core_api.OptimalResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OptimalResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> optim_path_;
    ::google::protobuf::RepeatedField<double> optim_control_;
    ::int32_t optim_path_size_row_;
    ::int32_t optim_path_size_col_;
    ::int32_t optim_control_size_row_;
    ::int32_t optim_control_size_col_;
    double functional_value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OptimalResponse_class_data_;
// -------------------------------------------------------------------

class OptimalRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:core_api.OptimalRequest) */ {
 public:
  inline OptimalRequest() : OptimalRequest(nullptr) {}
  ~OptimalRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OptimalRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OptimalRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OptimalRequest(::google::protobuf::internal::ConstantInitialized);

  inline OptimalRequest(const OptimalRequest& from) : OptimalRequest(nullptr, from) {}
  inline OptimalRequest(OptimalRequest&& from) noexcept
      : OptimalRequest(nullptr, ::std::move(from)) {}
  inline OptimalRequest& operator=(const OptimalRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OptimalRequest& operator=(OptimalRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OptimalRequest& default_instance() {
    return *reinterpret_cast<const OptimalRequest*>(
        &_OptimalRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(OptimalRequest& a, OptimalRequest& b) { a.Swap(&b); }
  inline void Swap(OptimalRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OptimalRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OptimalRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OptimalRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OptimalRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OptimalRequest& from) { OptimalRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OptimalRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "core_api.OptimalRequest"; }

  explicit OptimalRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OptimalRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OptimalRequest& from);
  OptimalRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OptimalRequest&& from) noexcept
      : OptimalRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEquationsFieldNumber = 1,
    kLinkedFieldNumber = 2,
    kU0FieldNumber = 4,
    kX0FieldNumber = 5,
    kHamiltonFieldNumber = 3,
    kT0FieldNumber = 6,
    kT1FieldNumber = 7,
    kTstepFieldNumber = 8,
    kDeltaFieldNumber = 9,
  };
  // repeated string equations = 1;
  int equations_size() const;
  private:
  int _internal_equations_size() const;

  public:
  void clear_equations() ;
  const ::std::string& equations(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_equations(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_equations(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_equations();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_equations(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& equations() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_equations();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_equations() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_equations();

  public:
  // repeated string linked = 2;
  int linked_size() const;
  private:
  int _internal_linked_size() const;

  public:
  void clear_linked() ;
  const ::std::string& linked(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_linked(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_linked(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_linked();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_linked(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& linked() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_linked();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_linked() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_linked();

  public:
  // repeated double u0 = 4;
  int u0_size() const;
  private:
  int _internal_u0_size() const;

  public:
  void clear_u0() ;
  double u0(int index) const;
  void set_u0(int index, double value);
  void add_u0(double value);
  const ::google::protobuf::RepeatedField<double>& u0() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_u0();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_u0() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_u0();

  public:
  // repeated double x0 = 5;
  int x0_size() const;
  private:
  int _internal_x0_size() const;

  public:
  void clear_x0() ;
  double x0(int index) const;
  void set_x0(int index, double value);
  void add_x0(double value);
  const ::google::protobuf::RepeatedField<double>& x0() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_x0();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_x0() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_x0();

  public:
  // string hamilton = 3;
  void clear_hamilton() ;
  const ::std::string& hamilton() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_hamilton(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_hamilton();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_hamilton();
  void set_allocated_hamilton(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_hamilton() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_hamilton(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_hamilton();

  public:
  // double t0 = 6;
  void clear_t0() ;
  double t0() const;
  void set_t0(double value);

  private:
  double _internal_t0() const;
  void _internal_set_t0(double value);

  public:
  // double t1 = 7;
  void clear_t1() ;
  double t1() const;
  void set_t1(double value);

  private:
  double _internal_t1() const;
  void _internal_set_t1(double value);

  public:
  // double tstep = 8;
  void clear_tstep() ;
  double tstep() const;
  void set_tstep(double value);

  private:
  double _internal_tstep() const;
  void _internal_set_tstep(double value);

  public:
  // double delta = 9;
  void clear_delta() ;
  double delta() const;
  void set_delta(double value);

  private:
  double _internal_delta() const;
  void _internal_set_delta(double value);

  public:
  // @@protoc_insertion_point(class_scope:core_api.OptimalRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 9,
                                   0, 63,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OptimalRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> equations_;
    ::google::protobuf::RepeatedPtrField<::std::string> linked_;
    ::google::protobuf::RepeatedField<double> u0_;
    ::google::protobuf::RepeatedField<double> x0_;
    ::google::protobuf::internal::ArenaStringPtr hamilton_;
    double t0_;
    double t1_;
    double tstep_;
    double delta_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OptimalRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// OptimalRequest

// repeated string equations = 1;
inline int OptimalRequest::_internal_equations_size() const {
  return _internal_equations().size();
}
inline int OptimalRequest::equations_size() const {
  return _internal_equations_size();
}
inline void OptimalRequest::clear_equations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.equations_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL OptimalRequest::add_equations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_equations()->Add();
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:core_api.OptimalRequest.equations)
  return _s;
}
inline const ::std::string& OptimalRequest::equations(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.equations)
  return _internal_equations().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL OptimalRequest::mutable_equations(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:core_api.OptimalRequest.equations)
  return _internal_mutable_equations()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void OptimalRequest::set_equations(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_equations()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.equations)
}
template <typename Arg_, typename... Args_>
inline void OptimalRequest::add_equations(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_equations(),
                               ::std::forward<Arg_>(value),
                               args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:core_api.OptimalRequest.equations)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& OptimalRequest::equations()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:core_api.OptimalRequest.equations)
  return _internal_equations();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
OptimalRequest::mutable_equations() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:core_api.OptimalRequest.equations)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_equations();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
OptimalRequest::_internal_equations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.equations_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
OptimalRequest::_internal_mutable_equations() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.equations_;
}

// repeated string linked = 2;
inline int OptimalRequest::_internal_linked_size() const {
  return _internal_linked().size();
}
inline int OptimalRequest::linked_size() const {
  return _internal_linked_size();
}
inline void OptimalRequest::clear_linked() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linked_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::std::string* PROTOBUF_NONNULL OptimalRequest::add_linked()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_linked()->Add();
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add_mutable:core_api.OptimalRequest.linked)
  return _s;
}
inline const ::std::string& OptimalRequest::linked(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.linked)
  return _internal_linked().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL OptimalRequest::mutable_linked(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:core_api.OptimalRequest.linked)
  return _internal_mutable_linked()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void OptimalRequest::set_linked(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_linked()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.linked)
}
template <typename Arg_, typename... Args_>
inline void OptimalRequest::add_linked(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_linked(),
                               ::std::forward<Arg_>(value),
                               args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:core_api.OptimalRequest.linked)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& OptimalRequest::linked()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:core_api.OptimalRequest.linked)
  return _internal_linked();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
OptimalRequest::mutable_linked() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:core_api.OptimalRequest.linked)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_linked();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
OptimalRequest::_internal_linked() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.linked_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
OptimalRequest::_internal_mutable_linked() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.linked_;
}

// string hamilton = 3;
inline void OptimalRequest::clear_hamilton() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hamilton_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& OptimalRequest::hamilton() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.hamilton)
  return _internal_hamilton();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void OptimalRequest::set_hamilton(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.hamilton_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.hamilton)
}
inline ::std::string* PROTOBUF_NONNULL OptimalRequest::mutable_hamilton()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_hamilton();
  // @@protoc_insertion_point(field_mutable:core_api.OptimalRequest.hamilton)
  return _s;
}
inline const ::std::string& OptimalRequest::_internal_hamilton() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hamilton_.Get();
}
inline void OptimalRequest::_internal_set_hamilton(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hamilton_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL OptimalRequest::_internal_mutable_hamilton() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hamilton_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE OptimalRequest::release_hamilton() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:core_api.OptimalRequest.hamilton)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.hamilton_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.hamilton_.Set("", GetArena());
  }
  return released;
}
inline void OptimalRequest::set_allocated_hamilton(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.hamilton_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hamilton_.IsDefault()) {
    _impl_.hamilton_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:core_api.OptimalRequest.hamilton)
}

// repeated double u0 = 4;
inline int OptimalRequest::_internal_u0_size() const {
  return _internal_u0().size();
}
inline int OptimalRequest::u0_size() const {
  return _internal_u0_size();
}
inline void OptimalRequest::clear_u0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u0_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double OptimalRequest::u0(int index) const {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.u0)
  return _internal_u0().Get(index);
}
inline void OptimalRequest::set_u0(int index, double value) {
  _internal_mutable_u0()->Set(index, value);
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.u0)
}
inline void OptimalRequest::add_u0(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_u0()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:core_api.OptimalRequest.u0)
}
inline const ::google::protobuf::RepeatedField<double>& OptimalRequest::u0() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:core_api.OptimalRequest.u0)
  return _internal_u0();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL OptimalRequest::mutable_u0()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:core_api.OptimalRequest.u0)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_u0();
}
inline const ::google::protobuf::RepeatedField<double>&
OptimalRequest::_internal_u0() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.u0_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
OptimalRequest::_internal_mutable_u0() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.u0_;
}

// repeated double x0 = 5;
inline int OptimalRequest::_internal_x0_size() const {
  return _internal_x0().size();
}
inline int OptimalRequest::x0_size() const {
  return _internal_x0_size();
}
inline void OptimalRequest::clear_x0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x0_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double OptimalRequest::x0(int index) const {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.x0)
  return _internal_x0().Get(index);
}
inline void OptimalRequest::set_x0(int index, double value) {
  _internal_mutable_x0()->Set(index, value);
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.x0)
}
inline void OptimalRequest::add_x0(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_x0()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_add:core_api.OptimalRequest.x0)
}
inline const ::google::protobuf::RepeatedField<double>& OptimalRequest::x0() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:core_api.OptimalRequest.x0)
  return _internal_x0();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL OptimalRequest::mutable_x0()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_mutable_list:core_api.OptimalRequest.x0)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_x0();
}
inline const ::google::protobuf::RepeatedField<double>&
OptimalRequest::_internal_x0() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x0_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
OptimalRequest::_internal_mutable_x0() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.x0_;
}

// double t0 = 6;
inline void OptimalRequest::clear_t0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.t0_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline double OptimalRequest::t0() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.t0)
  return _internal_t0();
}
inline void OptimalRequest::set_t0(double value) {
  _internal_set_t0(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.t0)
}
inline double OptimalRequest::_internal_t0() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.t0_;
}
inline void OptimalRequest::_internal_set_t0(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.t0_ = value;
}

// double t1 = 7;
inline void OptimalRequest::clear_t1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.t1_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double OptimalRequest::t1() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.t1)
  return _internal_t1();
}
inline void OptimalRequest::set_t1(double value) {
  _internal_set_t1(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.t1)
}
inline double OptimalRequest::_internal_t1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.t1_;
}
inline void OptimalRequest::_internal_set_t1(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.t1_ = value;
}

// double tstep = 8;
inline void OptimalRequest::clear_tstep() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tstep_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline double OptimalRequest::tstep() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.tstep)
  return _internal_tstep();
}
inline void OptimalRequest::set_tstep(double value) {
  _internal_set_tstep(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.tstep)
}
inline double OptimalRequest::_internal_tstep() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tstep_;
}
inline void OptimalRequest::_internal_set_tstep(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tstep_ = value;
}

// double delta = 9;
inline void OptimalRequest::clear_delta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.delta_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline double OptimalRequest::delta() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalRequest.delta)
  return _internal_delta();
}
inline void OptimalRequest::set_delta(double value) {
  _internal_set_delta(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:core_api.OptimalRequest.delta)
}
inline double OptimalRequest::_internal_delta() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.delta_;
}
inline void OptimalRequest::_internal_set_delta(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.delta_ = value;
}

// -------------------------------------------------------------------

// OptimalResponse

// repeated double optim_path = 1;
inline int OptimalResponse::_internal_optim_path_size() const {
  return _internal_optim_path().size();
}
inline int OptimalResponse::optim_path_size() const {
  return _internal_optim_path_size();
}
inline void OptimalResponse::clear_optim_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_path_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double OptimalResponse::optim_path(int index) const {
  // @@protoc_insertion_point(field_get:core_api.OptimalResponse.optim_path)
  return _internal_optim_path().Get(index);
}
inline void OptimalResponse::set_optim_path(int index, double value) {
  _internal_mutable_optim_path()->Set(index, value);
  // @@protoc_insertion_point(field_set:core_api.OptimalResponse.optim_path)
}
inline void OptimalResponse::add_optim_path(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_optim_path()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:core_api.OptimalResponse.optim_path)
}
inline const ::google::protobuf::RepeatedField<double>& OptimalResponse::optim_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:core_api.OptimalResponse.optim_path)
  return _internal_optim_path();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL OptimalResponse::mutable_optim_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:core_api.OptimalResponse.optim_path)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_optim_path();
}
inline const ::google::protobuf::RepeatedField<double>&
OptimalResponse::_internal_optim_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_path_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
OptimalResponse::_internal_mutable_optim_path() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.optim_path_;
}

// repeated double optim_control = 2;
inline int OptimalResponse::_internal_optim_control_size() const {
  return _internal_optim_control().size();
}
inline int OptimalResponse::optim_control_size() const {
  return _internal_optim_control_size();
}
inline void OptimalResponse::clear_optim_control() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_control_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double OptimalResponse::optim_control(int index) const {
  // @@protoc_insertion_point(field_get:core_api.OptimalResponse.optim_control)
  return _internal_optim_control().Get(index);
}
inline void OptimalResponse::set_optim_control(int index, double value) {
  _internal_mutable_optim_control()->Set(index, value);
  // @@protoc_insertion_point(field_set:core_api.OptimalResponse.optim_control)
}
inline void OptimalResponse::add_optim_control(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_optim_control()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:core_api.OptimalResponse.optim_control)
}
inline const ::google::protobuf::RepeatedField<double>& OptimalResponse::optim_control() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:core_api.OptimalResponse.optim_control)
  return _internal_optim_control();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL OptimalResponse::mutable_optim_control()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:core_api.OptimalResponse.optim_control)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_optim_control();
}
inline const ::google::protobuf::RepeatedField<double>&
OptimalResponse::_internal_optim_control() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_control_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
OptimalResponse::_internal_mutable_optim_control() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.optim_control_;
}

// int32 optim_path_size_row = 3;
inline void OptimalResponse::clear_optim_path_size_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_path_size_row_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t OptimalResponse::optim_path_size_row() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalResponse.optim_path_size_row)
  return _internal_optim_path_size_row();
}
inline void OptimalResponse::set_optim_path_size_row(::int32_t value) {
  _internal_set_optim_path_size_row(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:core_api.OptimalResponse.optim_path_size_row)
}
inline ::int32_t OptimalResponse::_internal_optim_path_size_row() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_path_size_row_;
}
inline void OptimalResponse::_internal_set_optim_path_size_row(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_path_size_row_ = value;
}

// int32 optim_path_size_col = 4;
inline void OptimalResponse::clear_optim_path_size_col() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_path_size_col_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t OptimalResponse::optim_path_size_col() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalResponse.optim_path_size_col)
  return _internal_optim_path_size_col();
}
inline void OptimalResponse::set_optim_path_size_col(::int32_t value) {
  _internal_set_optim_path_size_col(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:core_api.OptimalResponse.optim_path_size_col)
}
inline ::int32_t OptimalResponse::_internal_optim_path_size_col() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_path_size_col_;
}
inline void OptimalResponse::_internal_set_optim_path_size_col(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_path_size_col_ = value;
}

// int32 optim_control_size_row = 5;
inline void OptimalResponse::clear_optim_control_size_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_control_size_row_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t OptimalResponse::optim_control_size_row() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalResponse.optim_control_size_row)
  return _internal_optim_control_size_row();
}
inline void OptimalResponse::set_optim_control_size_row(::int32_t value) {
  _internal_set_optim_control_size_row(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:core_api.OptimalResponse.optim_control_size_row)
}
inline ::int32_t OptimalResponse::_internal_optim_control_size_row() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_control_size_row_;
}
inline void OptimalResponse::_internal_set_optim_control_size_row(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_control_size_row_ = value;
}

// int32 optim_control_size_col = 6;
inline void OptimalResponse::clear_optim_control_size_col() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_control_size_col_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t OptimalResponse::optim_control_size_col() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalResponse.optim_control_size_col)
  return _internal_optim_control_size_col();
}
inline void OptimalResponse::set_optim_control_size_col(::int32_t value) {
  _internal_set_optim_control_size_col(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:core_api.OptimalResponse.optim_control_size_col)
}
inline ::int32_t OptimalResponse::_internal_optim_control_size_col() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_control_size_col_;
}
inline void OptimalResponse::_internal_set_optim_control_size_col(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_control_size_col_ = value;
}

// double functional_value = 7;
inline void OptimalResponse::clear_functional_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.functional_value_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double OptimalResponse::functional_value() const {
  // @@protoc_insertion_point(field_get:core_api.OptimalResponse.functional_value)
  return _internal_functional_value();
}
inline void OptimalResponse::set_functional_value(double value) {
  _internal_set_functional_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:core_api.OptimalResponse.functional_value)
}
inline double OptimalResponse::_internal_functional_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.functional_value_;
}
inline void OptimalResponse::_internal_set_functional_value(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.functional_value_ = value;
}

// -------------------------------------------------------------------

// OptimizeParamsRequest

// double learning_rate = 1;
inline void OptimizeParamsRequest::clear_learning_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.learning_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double OptimizeParamsRequest::learning_rate() const {
  // @@protoc_insertion_point(field_get:core_api.OptimizeParamsRequest.learning_rate)
  return _internal_learning_rate();
}
inline void OptimizeParamsRequest::set_learning_rate(double value) {
  _internal_set_learning_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:core_api.OptimizeParamsRequest.learning_rate)
}
inline double OptimizeParamsRequest::_internal_learning_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.learning_rate_;
}
inline void OptimizeParamsRequest::_internal_set_learning_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.learning_rate_ = value;
}

// repeated double left_edge = 2;
inline int OptimizeParamsRequest::_internal_left_edge_size() const {
  return _internal_left_edge().size();
}
inline int OptimizeParamsRequest::left_edge_size() const {
  return _internal_left_edge_size();
}
inline void OptimizeParamsRequest::clear_left_edge() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_edge_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double OptimizeParamsRequest::left_edge(int index) const {
  // @@protoc_insertion_point(field_get:core_api.OptimizeParamsRequest.left_edge)
  return _internal_left_edge().Get(index);
}
inline void OptimizeParamsRequest::set_left_edge(int index, double value) {
  _internal_mutable_left_edge()->Set(index, value);
  // @@protoc_insertion_point(field_set:core_api.OptimizeParamsRequest.left_edge)
}
inline void OptimizeParamsRequest::add_left_edge(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_left_edge()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:core_api.OptimizeParamsRequest.left_edge)
}
inline const ::google::protobuf::RepeatedField<double>& OptimizeParamsRequest::left_edge() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:core_api.OptimizeParamsRequest.left_edge)
  return _internal_left_edge();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL OptimizeParamsRequest::mutable_left_edge()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:core_api.OptimizeParamsRequest.left_edge)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_left_edge();
}
inline const ::google::protobuf::RepeatedField<double>&
OptimizeParamsRequest::_internal_left_edge() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_edge_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
OptimizeParamsRequest::_internal_mutable_left_edge() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.left_edge_;
}

// repeated double right_edge = 3;
inline int OptimizeParamsRequest::_internal_right_edge_size() const {
  return _internal_right_edge().size();
}
inline int OptimizeParamsRequest::right_edge_size() const {
  return _internal_right_edge_size();
}
inline void OptimizeParamsRequest::clear_right_edge() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_edge_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double OptimizeParamsRequest::right_edge(int index) const {
  // @@protoc_insertion_point(field_get:core_api.OptimizeParamsRequest.right_edge)
  return _internal_right_edge().Get(index);
}
inline void OptimizeParamsRequest::set_right_edge(int index, double value) {
  _internal_mutable_right_edge()->Set(index, value);
  // @@protoc_insertion_point(field_set:core_api.OptimizeParamsRequest.right_edge)
}
inline void OptimizeParamsRequest::add_right_edge(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_right_edge()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:core_api.OptimizeParamsRequest.right_edge)
}
inline const ::google::protobuf::RepeatedField<double>& OptimizeParamsRequest::right_edge() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:core_api.OptimizeParamsRequest.right_edge)
  return _internal_right_edge();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL OptimizeParamsRequest::mutable_right_edge()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:core_api.OptimizeParamsRequest.right_edge)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_right_edge();
}
inline const ::google::protobuf::RepeatedField<double>&
OptimizeParamsRequest::_internal_right_edge() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_edge_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
OptimizeParamsRequest::_internal_mutable_right_edge() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.right_edge_;
}

// int32 epochs = 4;
inline void OptimizeParamsRequest::clear_epochs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.epochs_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t OptimizeParamsRequest::epochs() const {
  // @@protoc_insertion_point(field_get:core_api.OptimizeParamsRequest.epochs)
  return _internal_epochs();
}
inline void OptimizeParamsRequest::set_epochs(::int32_t value) {
  _internal_set_epochs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:core_api.OptimizeParamsRequest.epochs)
}
inline ::int32_t OptimizeParamsRequest::_internal_epochs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.epochs_;
}
inline void OptimizeParamsRequest::_internal_set_epochs(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.epochs_ = value;
}

// -------------------------------------------------------------------

// OptimizeParamsResponse

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace core_api


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // core_2eproto_2epb_2eh
