// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: core.proto
#ifndef GRPC_core_2eproto__INCLUDED
#define GRPC_core_2eproto__INCLUDED

#include "core.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace core_api {

class CoreOptimalControlService final {
 public:
  static constexpr char const* service_full_name() {
    return "core_api.CoreOptimalControlService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::core_api::OptimalResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimalResponse>> AsyncCalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimalResponse>>(AsyncCalcOptimalTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimalResponse>> PrepareAsyncCalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimalResponse>>(PrepareAsyncCalcOptimalTaskRaw(context, request, cq));
    }
    virtual ::grpc::Status SetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::core_api::OptimizeParamsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimizeParamsResponse>> AsyncSetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimizeParamsResponse>>(AsyncSetOptimizerParamsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimizeParamsResponse>> PrepareAsyncSetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimizeParamsResponse>>(PrepareAsyncSetOptimizerParamsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest* request, ::core_api::OptimalResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest* request, ::core_api::OptimalResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest* request, ::core_api::OptimizeParamsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest* request, ::core_api::OptimizeParamsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimalResponse>* AsyncCalcOptimalTaskRaw(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimalResponse>* PrepareAsyncCalcOptimalTaskRaw(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimizeParamsResponse>* AsyncSetOptimizerParamsRaw(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::core_api::OptimizeParamsResponse>* PrepareAsyncSetOptimizerParamsRaw(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::core_api::OptimalResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core_api::OptimalResponse>> AsyncCalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core_api::OptimalResponse>>(AsyncCalcOptimalTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core_api::OptimalResponse>> PrepareAsyncCalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core_api::OptimalResponse>>(PrepareAsyncCalcOptimalTaskRaw(context, request, cq));
    }
    ::grpc::Status SetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::core_api::OptimizeParamsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core_api::OptimizeParamsResponse>> AsyncSetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core_api::OptimizeParamsResponse>>(AsyncSetOptimizerParamsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core_api::OptimizeParamsResponse>> PrepareAsyncSetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core_api::OptimizeParamsResponse>>(PrepareAsyncSetOptimizerParamsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest* request, ::core_api::OptimalResponse* response, std::function<void(::grpc::Status)>) override;
      void CalcOptimalTask(::grpc::ClientContext* context, const ::core_api::OptimalRequest* request, ::core_api::OptimalResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest* request, ::core_api::OptimizeParamsResponse* response, std::function<void(::grpc::Status)>) override;
      void SetOptimizerParams(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest* request, ::core_api::OptimizeParamsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::core_api::OptimalResponse>* AsyncCalcOptimalTaskRaw(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::core_api::OptimalResponse>* PrepareAsyncCalcOptimalTaskRaw(::grpc::ClientContext* context, const ::core_api::OptimalRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::core_api::OptimizeParamsResponse>* AsyncSetOptimizerParamsRaw(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::core_api::OptimizeParamsResponse>* PrepareAsyncSetOptimizerParamsRaw(::grpc::ClientContext* context, const ::core_api::OptimizeParamsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CalcOptimalTask_;
    const ::grpc::internal::RpcMethod rpcmethod_SetOptimizerParams_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CalcOptimalTask(::grpc::ServerContext* context, const ::core_api::OptimalRequest* request, ::core_api::OptimalResponse* response);
    virtual ::grpc::Status SetOptimizerParams(::grpc::ServerContext* context, const ::core_api::OptimizeParamsRequest* request, ::core_api::OptimizeParamsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CalcOptimalTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CalcOptimalTask() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CalcOptimalTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcOptimalTask(::grpc::ServerContext* /*context*/, const ::core_api::OptimalRequest* /*request*/, ::core_api::OptimalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalcOptimalTask(::grpc::ServerContext* context, ::core_api::OptimalRequest* request, ::grpc::ServerAsyncResponseWriter< ::core_api::OptimalResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetOptimizerParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetOptimizerParams() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetOptimizerParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOptimizerParams(::grpc::ServerContext* /*context*/, const ::core_api::OptimizeParamsRequest* /*request*/, ::core_api::OptimizeParamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetOptimizerParams(::grpc::ServerContext* context, ::core_api::OptimizeParamsRequest* request, ::grpc::ServerAsyncResponseWriter< ::core_api::OptimizeParamsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CalcOptimalTask<WithAsyncMethod_SetOptimizerParams<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CalcOptimalTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CalcOptimalTask() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::core_api::OptimalRequest, ::core_api::OptimalResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::core_api::OptimalRequest* request, ::core_api::OptimalResponse* response) { return this->CalcOptimalTask(context, request, response); }));}
    void SetMessageAllocatorFor_CalcOptimalTask(
        ::grpc::MessageAllocator< ::core_api::OptimalRequest, ::core_api::OptimalResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::core_api::OptimalRequest, ::core_api::OptimalResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CalcOptimalTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcOptimalTask(::grpc::ServerContext* /*context*/, const ::core_api::OptimalRequest* /*request*/, ::core_api::OptimalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalcOptimalTask(
      ::grpc::CallbackServerContext* /*context*/, const ::core_api::OptimalRequest* /*request*/, ::core_api::OptimalResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetOptimizerParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetOptimizerParams() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::core_api::OptimizeParamsRequest, ::core_api::OptimizeParamsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::core_api::OptimizeParamsRequest* request, ::core_api::OptimizeParamsResponse* response) { return this->SetOptimizerParams(context, request, response); }));}
    void SetMessageAllocatorFor_SetOptimizerParams(
        ::grpc::MessageAllocator< ::core_api::OptimizeParamsRequest, ::core_api::OptimizeParamsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::core_api::OptimizeParamsRequest, ::core_api::OptimizeParamsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetOptimizerParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOptimizerParams(::grpc::ServerContext* /*context*/, const ::core_api::OptimizeParamsRequest* /*request*/, ::core_api::OptimizeParamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetOptimizerParams(
      ::grpc::CallbackServerContext* /*context*/, const ::core_api::OptimizeParamsRequest* /*request*/, ::core_api::OptimizeParamsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CalcOptimalTask<WithCallbackMethod_SetOptimizerParams<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CalcOptimalTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CalcOptimalTask() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CalcOptimalTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcOptimalTask(::grpc::ServerContext* /*context*/, const ::core_api::OptimalRequest* /*request*/, ::core_api::OptimalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetOptimizerParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetOptimizerParams() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetOptimizerParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOptimizerParams(::grpc::ServerContext* /*context*/, const ::core_api::OptimizeParamsRequest* /*request*/, ::core_api::OptimizeParamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CalcOptimalTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CalcOptimalTask() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CalcOptimalTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcOptimalTask(::grpc::ServerContext* /*context*/, const ::core_api::OptimalRequest* /*request*/, ::core_api::OptimalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalcOptimalTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetOptimizerParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetOptimizerParams() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetOptimizerParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOptimizerParams(::grpc::ServerContext* /*context*/, const ::core_api::OptimizeParamsRequest* /*request*/, ::core_api::OptimizeParamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetOptimizerParams(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CalcOptimalTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CalcOptimalTask() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CalcOptimalTask(context, request, response); }));
    }
    ~WithRawCallbackMethod_CalcOptimalTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcOptimalTask(::grpc::ServerContext* /*context*/, const ::core_api::OptimalRequest* /*request*/, ::core_api::OptimalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalcOptimalTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetOptimizerParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetOptimizerParams() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetOptimizerParams(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetOptimizerParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOptimizerParams(::grpc::ServerContext* /*context*/, const ::core_api::OptimizeParamsRequest* /*request*/, ::core_api::OptimizeParamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetOptimizerParams(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CalcOptimalTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CalcOptimalTask() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::core_api::OptimalRequest, ::core_api::OptimalResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::core_api::OptimalRequest, ::core_api::OptimalResponse>* streamer) {
                       return this->StreamedCalcOptimalTask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CalcOptimalTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CalcOptimalTask(::grpc::ServerContext* /*context*/, const ::core_api::OptimalRequest* /*request*/, ::core_api::OptimalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalcOptimalTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::core_api::OptimalRequest,::core_api::OptimalResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetOptimizerParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetOptimizerParams() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::core_api::OptimizeParamsRequest, ::core_api::OptimizeParamsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::core_api::OptimizeParamsRequest, ::core_api::OptimizeParamsResponse>* streamer) {
                       return this->StreamedSetOptimizerParams(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetOptimizerParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetOptimizerParams(::grpc::ServerContext* /*context*/, const ::core_api::OptimizeParamsRequest* /*request*/, ::core_api::OptimizeParamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetOptimizerParams(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::core_api::OptimizeParamsRequest,::core_api::OptimizeParamsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CalcOptimalTask<WithStreamedUnaryMethod_SetOptimizerParams<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CalcOptimalTask<WithStreamedUnaryMethod_SetOptimizerParams<Service > > StreamedService;
};

}  // namespace core_api


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_core_2eproto__INCLUDED
