// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tasks_api.proto
// Protobuf C++ Version: 6.33.0-dev

#ifndef tasks_5fapi_2eproto_2epb_2eh
#define tasks_5fapi_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_tasks_5fapi_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_tasks_5fapi_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_tasks_5fapi_2eproto;
}  // extern "C"
namespace tasks_api {
class CallEquationRequest;
struct CallEquationRequestDefaultTypeInternal;
extern CallEquationRequestDefaultTypeInternal _CallEquationRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CallEquationRequest_class_data_;
class CallEquationResponse;
struct CallEquationResponseDefaultTypeInternal;
extern CallEquationResponseDefaultTypeInternal _CallEquationResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CallEquationResponse_class_data_;
class CallLinkedRequest;
struct CallLinkedRequestDefaultTypeInternal;
extern CallLinkedRequestDefaultTypeInternal _CallLinkedRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CallLinkedRequest_class_data_;
class CallLinkedResponse;
struct CallLinkedResponseDefaultTypeInternal;
extern CallLinkedResponseDefaultTypeInternal _CallLinkedResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CallLinkedResponse_class_data_;
class CallParamSRequest;
struct CallParamSRequestDefaultTypeInternal;
extern CallParamSRequestDefaultTypeInternal _CallParamSRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CallParamSRequest_class_data_;
class CallParamSResponse;
struct CallParamSResponseDefaultTypeInternal;
extern CallParamSResponseDefaultTypeInternal _CallParamSResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CallParamSResponse_class_data_;
}  // namespace tasks_api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace tasks_api {

// ===================================================================


// -------------------------------------------------------------------

class CallParamSResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tasks_api.CallParamSResponse) */ {
 public:
  inline CallParamSResponse() : CallParamSResponse(nullptr) {}
  ~CallParamSResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CallParamSResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CallParamSResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CallParamSResponse(::google::protobuf::internal::ConstantInitialized);

  inline CallParamSResponse(const CallParamSResponse& from) : CallParamSResponse(nullptr, from) {}
  inline CallParamSResponse(CallParamSResponse&& from) noexcept
      : CallParamSResponse(nullptr, ::std::move(from)) {}
  inline CallParamSResponse& operator=(const CallParamSResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallParamSResponse& operator=(CallParamSResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallParamSResponse& default_instance() {
    return *reinterpret_cast<const CallParamSResponse*>(
        &_CallParamSResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(CallParamSResponse& a, CallParamSResponse& b) { a.Swap(&b); }
  inline void Swap(CallParamSResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallParamSResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallParamSResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CallParamSResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CallParamSResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CallParamSResponse& from) { CallParamSResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CallParamSResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "tasks_api.CallParamSResponse"; }

  explicit CallParamSResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CallParamSResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CallParamSResponse& from);
  CallParamSResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CallParamSResponse&& from) noexcept
      : CallParamSResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // double result = 1;
  void clear_result() ;
  double result() const;
  void set_result(double value);

  private:
  double _internal_result() const;
  void _internal_set_result(double value);

  public:
  // @@protoc_insertion_point(class_scope:tasks_api.CallParamSResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CallParamSResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tasks_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CallParamSResponse_class_data_;
// -------------------------------------------------------------------

class CallParamSRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tasks_api.CallParamSRequest) */ {
 public:
  inline CallParamSRequest() : CallParamSRequest(nullptr) {}
  ~CallParamSRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CallParamSRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CallParamSRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CallParamSRequest(::google::protobuf::internal::ConstantInitialized);

  inline CallParamSRequest(const CallParamSRequest& from) : CallParamSRequest(nullptr, from) {}
  inline CallParamSRequest(CallParamSRequest&& from) noexcept
      : CallParamSRequest(nullptr, ::std::move(from)) {}
  inline CallParamSRequest& operator=(const CallParamSRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallParamSRequest& operator=(CallParamSRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallParamSRequest& default_instance() {
    return *reinterpret_cast<const CallParamSRequest*>(
        &_CallParamSRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(CallParamSRequest& a, CallParamSRequest& b) { a.Swap(&b); }
  inline void Swap(CallParamSRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallParamSRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallParamSRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CallParamSRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CallParamSRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CallParamSRequest& from) { CallParamSRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CallParamSRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "tasks_api.CallParamSRequest"; }

  explicit CallParamSRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CallParamSRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CallParamSRequest& from);
  CallParamSRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CallParamSRequest&& from) noexcept
      : CallParamSRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kUFieldNumber = 4,
    kOptimUFieldNumber = 7,
    kXSizeRowFieldNumber = 2,
    kXSizeColFieldNumber = 3,
    kUSizeRowFieldNumber = 5,
    kUSizeColFieldNumber = 6,
    kOptimUSizeRowFieldNumber = 8,
    kOptimUSizeColFieldNumber = 9,
  };
  // repeated double x = 1;
  int x_size() const;
  private:
  int _internal_x_size() const;

  public:
  void clear_x() ;
  double x(int index) const;
  void set_x(int index, double value);
  void add_x(double value);
  const ::google::protobuf::RepeatedField<double>& x() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_x();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_x() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_x();

  public:
  // repeated double u = 4;
  int u_size() const;
  private:
  int _internal_u_size() const;

  public:
  void clear_u() ;
  double u(int index) const;
  void set_u(int index, double value);
  void add_u(double value);
  const ::google::protobuf::RepeatedField<double>& u() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_u();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_u() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_u();

  public:
  // repeated double optim_u = 7;
  int optim_u_size() const;
  private:
  int _internal_optim_u_size() const;

  public:
  void clear_optim_u() ;
  double optim_u(int index) const;
  void set_optim_u(int index, double value);
  void add_optim_u(double value);
  const ::google::protobuf::RepeatedField<double>& optim_u() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_optim_u();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_optim_u() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_optim_u();

  public:
  // int32 x_size_row = 2;
  void clear_x_size_row() ;
  ::int32_t x_size_row() const;
  void set_x_size_row(::int32_t value);

  private:
  ::int32_t _internal_x_size_row() const;
  void _internal_set_x_size_row(::int32_t value);

  public:
  // int32 x_size_col = 3;
  void clear_x_size_col() ;
  ::int32_t x_size_col() const;
  void set_x_size_col(::int32_t value);

  private:
  ::int32_t _internal_x_size_col() const;
  void _internal_set_x_size_col(::int32_t value);

  public:
  // int32 u_size_row = 5;
  void clear_u_size_row() ;
  ::int32_t u_size_row() const;
  void set_u_size_row(::int32_t value);

  private:
  ::int32_t _internal_u_size_row() const;
  void _internal_set_u_size_row(::int32_t value);

  public:
  // int32 u_size_col = 6;
  void clear_u_size_col() ;
  ::int32_t u_size_col() const;
  void set_u_size_col(::int32_t value);

  private:
  ::int32_t _internal_u_size_col() const;
  void _internal_set_u_size_col(::int32_t value);

  public:
  // int32 optim_u_size_row = 8;
  void clear_optim_u_size_row() ;
  ::int32_t optim_u_size_row() const;
  void set_optim_u_size_row(::int32_t value);

  private:
  ::int32_t _internal_optim_u_size_row() const;
  void _internal_set_optim_u_size_row(::int32_t value);

  public:
  // int32 optim_u_size_col = 9;
  void clear_optim_u_size_col() ;
  ::int32_t optim_u_size_col() const;
  void set_optim_u_size_col(::int32_t value);

  private:
  ::int32_t _internal_optim_u_size_col() const;
  void _internal_set_optim_u_size_col(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:tasks_api.CallParamSRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 9,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CallParamSRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> x_;
    ::google::protobuf::RepeatedField<double> u_;
    ::google::protobuf::RepeatedField<double> optim_u_;
    ::int32_t x_size_row_;
    ::int32_t x_size_col_;
    ::int32_t u_size_row_;
    ::int32_t u_size_col_;
    ::int32_t optim_u_size_row_;
    ::int32_t optim_u_size_col_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tasks_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CallParamSRequest_class_data_;
// -------------------------------------------------------------------

class CallLinkedResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tasks_api.CallLinkedResponse) */ {
 public:
  inline CallLinkedResponse() : CallLinkedResponse(nullptr) {}
  ~CallLinkedResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CallLinkedResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CallLinkedResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CallLinkedResponse(::google::protobuf::internal::ConstantInitialized);

  inline CallLinkedResponse(const CallLinkedResponse& from) : CallLinkedResponse(nullptr, from) {}
  inline CallLinkedResponse(CallLinkedResponse&& from) noexcept
      : CallLinkedResponse(nullptr, ::std::move(from)) {}
  inline CallLinkedResponse& operator=(const CallLinkedResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallLinkedResponse& operator=(CallLinkedResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallLinkedResponse& default_instance() {
    return *reinterpret_cast<const CallLinkedResponse*>(
        &_CallLinkedResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(CallLinkedResponse& a, CallLinkedResponse& b) { a.Swap(&b); }
  inline void Swap(CallLinkedResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallLinkedResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallLinkedResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CallLinkedResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CallLinkedResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CallLinkedResponse& from) { CallLinkedResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CallLinkedResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "tasks_api.CallLinkedResponse"; }

  explicit CallLinkedResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CallLinkedResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CallLinkedResponse& from);
  CallLinkedResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CallLinkedResponse&& from) noexcept
      : CallLinkedResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // double result = 1;
  void clear_result() ;
  double result() const;
  void set_result(double value);

  private:
  double _internal_result() const;
  void _internal_set_result(double value);

  public:
  // @@protoc_insertion_point(class_scope:tasks_api.CallLinkedResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CallLinkedResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tasks_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CallLinkedResponse_class_data_;
// -------------------------------------------------------------------

class CallLinkedRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tasks_api.CallLinkedRequest) */ {
 public:
  inline CallLinkedRequest() : CallLinkedRequest(nullptr) {}
  ~CallLinkedRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CallLinkedRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CallLinkedRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CallLinkedRequest(::google::protobuf::internal::ConstantInitialized);

  inline CallLinkedRequest(const CallLinkedRequest& from) : CallLinkedRequest(nullptr, from) {}
  inline CallLinkedRequest(CallLinkedRequest&& from) noexcept
      : CallLinkedRequest(nullptr, ::std::move(from)) {}
  inline CallLinkedRequest& operator=(const CallLinkedRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallLinkedRequest& operator=(CallLinkedRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallLinkedRequest& default_instance() {
    return *reinterpret_cast<const CallLinkedRequest*>(
        &_CallLinkedRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CallLinkedRequest& a, CallLinkedRequest& b) { a.Swap(&b); }
  inline void Swap(CallLinkedRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallLinkedRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallLinkedRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CallLinkedRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CallLinkedRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CallLinkedRequest& from) { CallLinkedRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CallLinkedRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "tasks_api.CallLinkedRequest"; }

  explicit CallLinkedRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CallLinkedRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CallLinkedRequest& from);
  CallLinkedRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CallLinkedRequest&& from) noexcept
      : CallLinkedRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kParamsFieldNumber = 3,
    kArgFieldNumber = 2,
    kIdFieldNumber = 1,
    kSizeRowFieldNumber = 4,
    kSizeColFieldNumber = 5,
  };
  // repeated double params = 3;
  int params_size() const;
  private:
  int _internal_params_size() const;

  public:
  void clear_params() ;
  double params(int index) const;
  void set_params(int index, double value);
  void add_params(double value);
  const ::google::protobuf::RepeatedField<double>& params() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_params();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_params() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_params();

  public:
  // double arg = 2;
  void clear_arg() ;
  double arg() const;
  void set_arg(double value);

  private:
  double _internal_arg() const;
  void _internal_set_arg(double value);

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // int32 size_row = 4;
  void clear_size_row() ;
  ::int32_t size_row() const;
  void set_size_row(::int32_t value);

  private:
  ::int32_t _internal_size_row() const;
  void _internal_set_size_row(::int32_t value);

  public:
  // int32 size_col = 5;
  void clear_size_col() ;
  ::int32_t size_col() const;
  void set_size_col(::int32_t value);

  private:
  ::int32_t _internal_size_col() const;
  void _internal_set_size_col(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:tasks_api.CallLinkedRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CallLinkedRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> params_;
    double arg_;
    ::int32_t id_;
    ::int32_t size_row_;
    ::int32_t size_col_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tasks_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CallLinkedRequest_class_data_;
// -------------------------------------------------------------------

class CallEquationResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tasks_api.CallEquationResponse) */ {
 public:
  inline CallEquationResponse() : CallEquationResponse(nullptr) {}
  ~CallEquationResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CallEquationResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CallEquationResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CallEquationResponse(::google::protobuf::internal::ConstantInitialized);

  inline CallEquationResponse(const CallEquationResponse& from) : CallEquationResponse(nullptr, from) {}
  inline CallEquationResponse(CallEquationResponse&& from) noexcept
      : CallEquationResponse(nullptr, ::std::move(from)) {}
  inline CallEquationResponse& operator=(const CallEquationResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallEquationResponse& operator=(CallEquationResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallEquationResponse& default_instance() {
    return *reinterpret_cast<const CallEquationResponse*>(
        &_CallEquationResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CallEquationResponse& a, CallEquationResponse& b) { a.Swap(&b); }
  inline void Swap(CallEquationResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallEquationResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallEquationResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CallEquationResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CallEquationResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CallEquationResponse& from) { CallEquationResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CallEquationResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "tasks_api.CallEquationResponse"; }

  explicit CallEquationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CallEquationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CallEquationResponse& from);
  CallEquationResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CallEquationResponse&& from) noexcept
      : CallEquationResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // double result = 1;
  void clear_result() ;
  double result() const;
  void set_result(double value);

  private:
  double _internal_result() const;
  void _internal_set_result(double value);

  public:
  // @@protoc_insertion_point(class_scope:tasks_api.CallEquationResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CallEquationResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tasks_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CallEquationResponse_class_data_;
// -------------------------------------------------------------------

class CallEquationRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tasks_api.CallEquationRequest) */ {
 public:
  inline CallEquationRequest() : CallEquationRequest(nullptr) {}
  ~CallEquationRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CallEquationRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CallEquationRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CallEquationRequest(::google::protobuf::internal::ConstantInitialized);

  inline CallEquationRequest(const CallEquationRequest& from) : CallEquationRequest(nullptr, from) {}
  inline CallEquationRequest(CallEquationRequest&& from) noexcept
      : CallEquationRequest(nullptr, ::std::move(from)) {}
  inline CallEquationRequest& operator=(const CallEquationRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallEquationRequest& operator=(CallEquationRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallEquationRequest& default_instance() {
    return *reinterpret_cast<const CallEquationRequest*>(
        &_CallEquationRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CallEquationRequest& a, CallEquationRequest& b) { a.Swap(&b); }
  inline void Swap(CallEquationRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallEquationRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallEquationRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CallEquationRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CallEquationRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CallEquationRequest& from) { CallEquationRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CallEquationRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "tasks_api.CallEquationRequest"; }

  explicit CallEquationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CallEquationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CallEquationRequest& from);
  CallEquationRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CallEquationRequest&& from) noexcept
      : CallEquationRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kParamsFieldNumber = 3,
    kArgFieldNumber = 2,
    kIdFieldNumber = 1,
    kSizeRowFieldNumber = 4,
    kSizeColFieldNumber = 5,
  };
  // repeated double params = 3;
  int params_size() const;
  private:
  int _internal_params_size() const;

  public:
  void clear_params() ;
  double params(int index) const;
  void set_params(int index, double value);
  void add_params(double value);
  const ::google::protobuf::RepeatedField<double>& params() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_params();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_params() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_params();

  public:
  // double arg = 2;
  void clear_arg() ;
  double arg() const;
  void set_arg(double value);

  private:
  double _internal_arg() const;
  void _internal_set_arg(double value);

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // int32 size_row = 4;
  void clear_size_row() ;
  ::int32_t size_row() const;
  void set_size_row(::int32_t value);

  private:
  ::int32_t _internal_size_row() const;
  void _internal_set_size_row(::int32_t value);

  public:
  // int32 size_col = 5;
  void clear_size_col() ;
  ::int32_t size_col() const;
  void set_size_col(::int32_t value);

  private:
  ::int32_t _internal_size_col() const;
  void _internal_set_size_col(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:tasks_api.CallEquationRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CallEquationRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> params_;
    double arg_;
    ::int32_t id_;
    ::int32_t size_row_;
    ::int32_t size_col_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tasks_5fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CallEquationRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CallEquationRequest

// int32 id = 1;
inline void CallEquationRequest::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t CallEquationRequest::id() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallEquationRequest.id)
  return _internal_id();
}
inline void CallEquationRequest::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:tasks_api.CallEquationRequest.id)
}
inline ::int32_t CallEquationRequest::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void CallEquationRequest::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// double arg = 2;
inline void CallEquationRequest::clear_arg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arg_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double CallEquationRequest::arg() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallEquationRequest.arg)
  return _internal_arg();
}
inline void CallEquationRequest::set_arg(double value) {
  _internal_set_arg(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:tasks_api.CallEquationRequest.arg)
}
inline double CallEquationRequest::_internal_arg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.arg_;
}
inline void CallEquationRequest::_internal_set_arg(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arg_ = value;
}

// repeated double params = 3;
inline int CallEquationRequest::_internal_params_size() const {
  return _internal_params().size();
}
inline int CallEquationRequest::params_size() const {
  return _internal_params_size();
}
inline void CallEquationRequest::clear_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.params_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double CallEquationRequest::params(int index) const {
  // @@protoc_insertion_point(field_get:tasks_api.CallEquationRequest.params)
  return _internal_params().Get(index);
}
inline void CallEquationRequest::set_params(int index, double value) {
  _internal_mutable_params()->Set(index, value);
  // @@protoc_insertion_point(field_set:tasks_api.CallEquationRequest.params)
}
inline void CallEquationRequest::add_params(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_params()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:tasks_api.CallEquationRequest.params)
}
inline const ::google::protobuf::RepeatedField<double>& CallEquationRequest::params() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tasks_api.CallEquationRequest.params)
  return _internal_params();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL CallEquationRequest::mutable_params()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:tasks_api.CallEquationRequest.params)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_params();
}
inline const ::google::protobuf::RepeatedField<double>&
CallEquationRequest::_internal_params() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.params_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
CallEquationRequest::_internal_mutable_params() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.params_;
}

// int32 size_row = 4;
inline void CallEquationRequest::clear_size_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_row_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t CallEquationRequest::size_row() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallEquationRequest.size_row)
  return _internal_size_row();
}
inline void CallEquationRequest::set_size_row(::int32_t value) {
  _internal_set_size_row(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:tasks_api.CallEquationRequest.size_row)
}
inline ::int32_t CallEquationRequest::_internal_size_row() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_row_;
}
inline void CallEquationRequest::_internal_set_size_row(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_row_ = value;
}

// int32 size_col = 5;
inline void CallEquationRequest::clear_size_col() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_col_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t CallEquationRequest::size_col() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallEquationRequest.size_col)
  return _internal_size_col();
}
inline void CallEquationRequest::set_size_col(::int32_t value) {
  _internal_set_size_col(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:tasks_api.CallEquationRequest.size_col)
}
inline ::int32_t CallEquationRequest::_internal_size_col() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_col_;
}
inline void CallEquationRequest::_internal_set_size_col(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_col_ = value;
}

// -------------------------------------------------------------------

// CallEquationResponse

// double result = 1;
inline void CallEquationResponse::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double CallEquationResponse::result() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallEquationResponse.result)
  return _internal_result();
}
inline void CallEquationResponse::set_result(double value) {
  _internal_set_result(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:tasks_api.CallEquationResponse.result)
}
inline double CallEquationResponse::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline void CallEquationResponse::_internal_set_result(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = value;
}

// -------------------------------------------------------------------

// CallLinkedRequest

// int32 id = 1;
inline void CallLinkedRequest::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t CallLinkedRequest::id() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallLinkedRequest.id)
  return _internal_id();
}
inline void CallLinkedRequest::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:tasks_api.CallLinkedRequest.id)
}
inline ::int32_t CallLinkedRequest::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void CallLinkedRequest::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// double arg = 2;
inline void CallLinkedRequest::clear_arg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arg_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double CallLinkedRequest::arg() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallLinkedRequest.arg)
  return _internal_arg();
}
inline void CallLinkedRequest::set_arg(double value) {
  _internal_set_arg(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:tasks_api.CallLinkedRequest.arg)
}
inline double CallLinkedRequest::_internal_arg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.arg_;
}
inline void CallLinkedRequest::_internal_set_arg(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arg_ = value;
}

// repeated double params = 3;
inline int CallLinkedRequest::_internal_params_size() const {
  return _internal_params().size();
}
inline int CallLinkedRequest::params_size() const {
  return _internal_params_size();
}
inline void CallLinkedRequest::clear_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.params_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double CallLinkedRequest::params(int index) const {
  // @@protoc_insertion_point(field_get:tasks_api.CallLinkedRequest.params)
  return _internal_params().Get(index);
}
inline void CallLinkedRequest::set_params(int index, double value) {
  _internal_mutable_params()->Set(index, value);
  // @@protoc_insertion_point(field_set:tasks_api.CallLinkedRequest.params)
}
inline void CallLinkedRequest::add_params(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_params()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:tasks_api.CallLinkedRequest.params)
}
inline const ::google::protobuf::RepeatedField<double>& CallLinkedRequest::params() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tasks_api.CallLinkedRequest.params)
  return _internal_params();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL CallLinkedRequest::mutable_params()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:tasks_api.CallLinkedRequest.params)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_params();
}
inline const ::google::protobuf::RepeatedField<double>&
CallLinkedRequest::_internal_params() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.params_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
CallLinkedRequest::_internal_mutable_params() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.params_;
}

// int32 size_row = 4;
inline void CallLinkedRequest::clear_size_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_row_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t CallLinkedRequest::size_row() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallLinkedRequest.size_row)
  return _internal_size_row();
}
inline void CallLinkedRequest::set_size_row(::int32_t value) {
  _internal_set_size_row(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:tasks_api.CallLinkedRequest.size_row)
}
inline ::int32_t CallLinkedRequest::_internal_size_row() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_row_;
}
inline void CallLinkedRequest::_internal_set_size_row(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_row_ = value;
}

// int32 size_col = 5;
inline void CallLinkedRequest::clear_size_col() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_col_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t CallLinkedRequest::size_col() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallLinkedRequest.size_col)
  return _internal_size_col();
}
inline void CallLinkedRequest::set_size_col(::int32_t value) {
  _internal_set_size_col(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:tasks_api.CallLinkedRequest.size_col)
}
inline ::int32_t CallLinkedRequest::_internal_size_col() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_col_;
}
inline void CallLinkedRequest::_internal_set_size_col(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_col_ = value;
}

// -------------------------------------------------------------------

// CallLinkedResponse

// double result = 1;
inline void CallLinkedResponse::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double CallLinkedResponse::result() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallLinkedResponse.result)
  return _internal_result();
}
inline void CallLinkedResponse::set_result(double value) {
  _internal_set_result(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:tasks_api.CallLinkedResponse.result)
}
inline double CallLinkedResponse::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline void CallLinkedResponse::_internal_set_result(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = value;
}

// -------------------------------------------------------------------

// CallParamSRequest

// repeated double x = 1;
inline int CallParamSRequest::_internal_x_size() const {
  return _internal_x().size();
}
inline int CallParamSRequest::x_size() const {
  return _internal_x_size();
}
inline void CallParamSRequest::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double CallParamSRequest::x(int index) const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.x)
  return _internal_x().Get(index);
}
inline void CallParamSRequest::set_x(int index, double value) {
  _internal_mutable_x()->Set(index, value);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.x)
}
inline void CallParamSRequest::add_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_x()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:tasks_api.CallParamSRequest.x)
}
inline const ::google::protobuf::RepeatedField<double>& CallParamSRequest::x() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tasks_api.CallParamSRequest.x)
  return _internal_x();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL CallParamSRequest::mutable_x()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:tasks_api.CallParamSRequest.x)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_x();
}
inline const ::google::protobuf::RepeatedField<double>&
CallParamSRequest::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
CallParamSRequest::_internal_mutable_x() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.x_;
}

// int32 x_size_row = 2;
inline void CallParamSRequest::clear_x_size_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_size_row_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t CallParamSRequest::x_size_row() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.x_size_row)
  return _internal_x_size_row();
}
inline void CallParamSRequest::set_x_size_row(::int32_t value) {
  _internal_set_x_size_row(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.x_size_row)
}
inline ::int32_t CallParamSRequest::_internal_x_size_row() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_size_row_;
}
inline void CallParamSRequest::_internal_set_x_size_row(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_size_row_ = value;
}

// int32 x_size_col = 3;
inline void CallParamSRequest::clear_x_size_col() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_size_col_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t CallParamSRequest::x_size_col() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.x_size_col)
  return _internal_x_size_col();
}
inline void CallParamSRequest::set_x_size_col(::int32_t value) {
  _internal_set_x_size_col(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.x_size_col)
}
inline ::int32_t CallParamSRequest::_internal_x_size_col() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_size_col_;
}
inline void CallParamSRequest::_internal_set_x_size_col(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_size_col_ = value;
}

// repeated double u = 4;
inline int CallParamSRequest::_internal_u_size() const {
  return _internal_u().size();
}
inline int CallParamSRequest::u_size() const {
  return _internal_u_size();
}
inline void CallParamSRequest::clear_u() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double CallParamSRequest::u(int index) const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.u)
  return _internal_u().Get(index);
}
inline void CallParamSRequest::set_u(int index, double value) {
  _internal_mutable_u()->Set(index, value);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.u)
}
inline void CallParamSRequest::add_u(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_u()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:tasks_api.CallParamSRequest.u)
}
inline const ::google::protobuf::RepeatedField<double>& CallParamSRequest::u() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tasks_api.CallParamSRequest.u)
  return _internal_u();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL CallParamSRequest::mutable_u()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:tasks_api.CallParamSRequest.u)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_u();
}
inline const ::google::protobuf::RepeatedField<double>&
CallParamSRequest::_internal_u() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.u_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
CallParamSRequest::_internal_mutable_u() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.u_;
}

// int32 u_size_row = 5;
inline void CallParamSRequest::clear_u_size_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u_size_row_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t CallParamSRequest::u_size_row() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.u_size_row)
  return _internal_u_size_row();
}
inline void CallParamSRequest::set_u_size_row(::int32_t value) {
  _internal_set_u_size_row(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.u_size_row)
}
inline ::int32_t CallParamSRequest::_internal_u_size_row() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.u_size_row_;
}
inline void CallParamSRequest::_internal_set_u_size_row(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u_size_row_ = value;
}

// int32 u_size_col = 6;
inline void CallParamSRequest::clear_u_size_col() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u_size_col_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t CallParamSRequest::u_size_col() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.u_size_col)
  return _internal_u_size_col();
}
inline void CallParamSRequest::set_u_size_col(::int32_t value) {
  _internal_set_u_size_col(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.u_size_col)
}
inline ::int32_t CallParamSRequest::_internal_u_size_col() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.u_size_col_;
}
inline void CallParamSRequest::_internal_set_u_size_col(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u_size_col_ = value;
}

// repeated double optim_u = 7;
inline int CallParamSRequest::_internal_optim_u_size() const {
  return _internal_optim_u().size();
}
inline int CallParamSRequest::optim_u_size() const {
  return _internal_optim_u_size();
}
inline void CallParamSRequest::clear_optim_u() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_u_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double CallParamSRequest::optim_u(int index) const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.optim_u)
  return _internal_optim_u().Get(index);
}
inline void CallParamSRequest::set_optim_u(int index, double value) {
  _internal_mutable_optim_u()->Set(index, value);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.optim_u)
}
inline void CallParamSRequest::add_optim_u(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_optim_u()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:tasks_api.CallParamSRequest.optim_u)
}
inline const ::google::protobuf::RepeatedField<double>& CallParamSRequest::optim_u() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:tasks_api.CallParamSRequest.optim_u)
  return _internal_optim_u();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL CallParamSRequest::mutable_optim_u()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:tasks_api.CallParamSRequest.optim_u)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_optim_u();
}
inline const ::google::protobuf::RepeatedField<double>&
CallParamSRequest::_internal_optim_u() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_u_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
CallParamSRequest::_internal_mutable_optim_u() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.optim_u_;
}

// int32 optim_u_size_row = 8;
inline void CallParamSRequest::clear_optim_u_size_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_u_size_row_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int32_t CallParamSRequest::optim_u_size_row() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.optim_u_size_row)
  return _internal_optim_u_size_row();
}
inline void CallParamSRequest::set_optim_u_size_row(::int32_t value) {
  _internal_set_optim_u_size_row(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.optim_u_size_row)
}
inline ::int32_t CallParamSRequest::_internal_optim_u_size_row() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_u_size_row_;
}
inline void CallParamSRequest::_internal_set_optim_u_size_row(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_u_size_row_ = value;
}

// int32 optim_u_size_col = 9;
inline void CallParamSRequest::clear_optim_u_size_col() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_u_size_col_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::int32_t CallParamSRequest::optim_u_size_col() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSRequest.optim_u_size_col)
  return _internal_optim_u_size_col();
}
inline void CallParamSRequest::set_optim_u_size_col(::int32_t value) {
  _internal_set_optim_u_size_col(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSRequest.optim_u_size_col)
}
inline ::int32_t CallParamSRequest::_internal_optim_u_size_col() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optim_u_size_col_;
}
inline void CallParamSRequest::_internal_set_optim_u_size_col(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optim_u_size_col_ = value;
}

// -------------------------------------------------------------------

// CallParamSResponse

// double result = 1;
inline void CallParamSResponse::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double CallParamSResponse::result() const {
  // @@protoc_insertion_point(field_get:tasks_api.CallParamSResponse.result)
  return _internal_result();
}
inline void CallParamSResponse::set_result(double value) {
  _internal_set_result(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:tasks_api.CallParamSResponse.result)
}
inline double CallParamSResponse::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline void CallParamSResponse::_internal_set_result(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace tasks_api


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // tasks_5fapi_2eproto_2epb_2eh
